# Generated by Django 4.2.4 on 2023-12-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofertas',
            name='fechaInicio',
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='mensaje',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
