# Generated by Django 4.2.4 on 2023-12-28 03:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_remove_ofertas_fechainicio_alter_comentarios_mensaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertas',
            name='fechaInicio',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
