# Generated by Django 4.2.4 on 2024-01-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_comentarios_fechacreacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='usuarioCreacion',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
