# Generated by Django 4.2.4 on 2024-01-16 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_comentarios_idproducto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='idProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentarios_listado', to='auctions.listado'),
        ),
        migrations.AlterField(
            model_name='listado',
            name='idCategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listado_categoria', to='auctions.categorias'),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='idProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ofertas_listado', to='auctions.listado'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='idProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='watchlist_listado', to='auctions.listado'),
        ),
    ]
