# Generated by Django 4.2.4 on 2024-01-17 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_comentarios_idproducto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='idProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentariosListado', to='auctions.listado'),
        ),
        migrations.AlterField(
            model_name='listado',
            name='idCategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listadoCategoria', to='auctions.categorias'),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='idProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ofertasListado', to='auctions.listado'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='idProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='watchlistListado', to='auctions.listado'),
        ),
    ]
