# Generated by Django 4.2.4 on 2024-01-30 02:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_comentarios_idproducto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='imagenUrl',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
