# Generated by Django 4.2.4 on 2024-01-30 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_categorias_imagenurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorias',
            old_name='imagenUrl',
            new_name='imagen',
        ),
    ]
